bucket         = "terraform-remote-backend-wenqi-test"
key            = "customer-service-secrets/state.tfstate"
region         = "us-east-1"
encrypt        = "true"
dynamodb_table = "terraform_state_lock"
